name: RepairReminder
version: 0.0.2
main: meowso.me.repairreminder.RepairReminder
api-version: 1.18
authors: [meowsome]
description: Prevent breaking of tool if durability is too low but prevent use of it until it is repaired
permissions:
  repairreminder.remind:
    description: Prevents held item from breaking, prevents block from being broken, and notifies user
    default: false